# Generated by Django 4.2.16 on 2024-12-01 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(help_text='Name your bird watching trip (Max 75 characters)', max_length=75, unique=True)),
                ('description', models.CharField(help_text='Bird Watching Location (Max 200 characters)', max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Not Seen', 'Not Seen'), ('Spotted', 'Spotted')], default='Not Seen', help_text='Did you see any? (Choices: Not Seen, Spotted)', max_length=8)),
                ('number_seen', models.IntegerField(default=0)),
                ('check_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.checklist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='bird',
            constraint=models.UniqueConstraint(fields=('bird_name', 'check_list'), name='unique_bird_per_checklist'),
        ),
    ]
