# Generated by Django 4.2.16 on 2024-12-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='description',
            field=models.CharField(help_text='(Max 200 characters)', max_length=200),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='list_name',
            field=models.CharField(help_text='(Max 75 characters)', max_length=75),
        ),
        migrations.AddConstraint(
            model_name='checklist',
            constraint=models.UniqueConstraint(fields=('user', 'list_name'), name='unique_user_list_name'),
        ),
    ]
